### ISSUE TITLE
TypeError when retrieving array with getHaystackData()

### ISSUE THREAD

**Issue by ffoods** [Sammyjo20/laravel-haystack#33]
Hi,

I'm saving an array with `getHaystackData()` in one job:

```
$this->setHaystackData('pendingTransactions', $pendingTransactions,  'array');

```

Then in another job in the chain, I retrieve the data like so:

```
$this->pendingTransactions = $this->getHaystackData('pendingTransactions');
```

That throws `TypeError: json_decode(): Argument #1 ($json) must be of type string, resource given`

Stack:
```
TypeError: json_decode(): Argument #1 ($json) must be of type string, resource given
#43 /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(1233): json_decode
#42 /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(1233): Illuminate\Database\Eloquent\Model::fromJson
#41 /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(743): Illuminate\Database\Eloquent\Model::castAttribute
#40 /vendor/sammyjo20/laravel-haystack/src/Models/HaystackData.php(73): Sammyjo20\LaravelHaystack\Models\HaystackData::getValueAttribute
#39 /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(631): Illuminate\Database\Eloquent\Model::mutateAttribute
#38 /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(2031): Illuminate\Database\Eloquent\Model::transformModelValue
#37 /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(462): Illuminate\Database\Eloquent\Model::getAttributeValue
#36 /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(441): Illuminate\Database\Eloquent\Model::getAttribute
#35 /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2120): Illuminate\Database\Eloquent\Model::__get
#34 /vendor/sammyjo20/laravel-haystack/src/Concerns/ManagesBales.php(342): Sammyjo20\LaravelHaystack\Models\Haystack::Sammyjo20\LaravelHaystack\Concerns\{closure}
#33 /vendor/laravel/framework/src/Illuminate/Collections/Collection.php(770): Illuminate\Support\Collection::mapWithKeys
#32 /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Collection.php(379): Illuminate\Database\Eloquent\Collection::mapWithKeys
#31 /vendor/sammyjo20/laravel-haystack/src/Concerns/ManagesBales.php(343): Sammyjo20\LaravelHaystack\Models\Haystack::allData
#30 /vendor/sammyjo20/laravel-haystack/src/Concerns/ManagesBales.php(356): Sammyjo20\LaravelHaystack\Models\Haystack::conditionallyGetAllData
#29 /vendor/sammyjo20/laravel-haystack/src/Concerns/ManagesBales.php(187): Sammyjo20\LaravelHaystack\Models\Haystack::finish
#28 /vendor/sammyjo20/laravel-haystack/src/Concerns/ManagesBales.php(213): Sammyjo20\LaravelHaystack\Models\Haystack::fail
#27 /vendor/sammyjo20/laravel-haystack/src/JobEventListener.php(137): Sammyjo20\LaravelHaystack\JobEventListener::handleFailedJob
#26 /vendor/sammyjo20/laravel-haystack/src/LaravelHaystackServiceProvider.php(69): Sammyjo20\LaravelHaystack\LaravelHaystackServiceProvider::Sammyjo20\LaravelHaystack\{closure}
#25 /vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(421): Illuminate\Events\Dispatcher::Illuminate\Events\{closure}
#24 /vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\Events\Dispatcher::dispatch
#23 /vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(195): Illuminate\Queue\Jobs\Job::fail
#22 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(582): Illuminate\Queue\Worker::failJob
#21 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(528): Illuminate\Queue\Worker::markJobAsFailedIfWillExceedMaxAttempts
#20 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(452): Illuminate\Queue\Worker::handleJobException
#19 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(429): Illuminate\Queue\Worker::process
#18 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(375): Illuminate\Queue\Worker::runJob
#17 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(173): Illuminate\Queue\Worker::daemon
#16 /vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(150): Illuminate\Queue\Console\WorkCommand::runWorker
#15 /vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(134): Illuminate\Queue\Console\WorkCommand::handle
#14 /vendor/laravel/horizon/src/Console/WorkCommand.php(51): Laravel\Horizon\Console\WorkCommand::handle
#13 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}
#12 /vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\Util::unwrapIfClosure
#11 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\BoundMethod::callBoundMethod
#10 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::call
#9 /vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\Container::call
#8 /vendor/laravel/framework/src/Illuminate/Console/Command.php(144): Illuminate\Console\Command::execute
#7 /vendor/symfony/console/Command/Command.php(308): Symfony\Component\Console\Command\Command::run
#6 /vendor/laravel/framework/src/Illuminate/Console/Command.php(126): Illuminate\Console\Command::run
#5 /vendor/symfony/console/Application.php(1002): Symfony\Component\Console\Application::doRunCommand
#4 /vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application::doRun
#3 /vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application::run
#2 /vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Illuminate\Console\Application::run
#1 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Foundation\Console\Kernel::handle
```

PHP 8.1, on latest Laravel and laravel-haystack, migrations were migrated.

**Comment by Sammyjo20** [comment]
Thanks for letting me know. I’m currently on holiday but I will take a look as soon as I’m back in a couple of days!

**Comment by Sammyjo20** [comment]
Hey @ffoods I set this up with the environment you have, and I couldn't seem to replicate the issue - this was my setup.

Haystack

```php
Haystack::build()
            ->addJob(new TestJob)
            ->addJob(new GetJob)
            ->dispatch();
```

TestJob.php

```php
/**
 * Execute the job.
 *
 * @return void
 */
public function handle()
{
    $this->setHaystackData('example', ['a' => 'b'], 'array');
}
```

GetJob.php

```php
/**
 * Execute the job.
 *
 * @return void
 */
public function handle()
{
    ray($this->getHaystackData('example'))->purple();
}
```

What database connection are you using and if you are able to share with me any of the data going into the setHaystackData that would be super!

Thanks
Sam

**Comment by Sammyjo20** [comment]
Closing as issue is stale
